syntax on
set autoindent
set autoread
set clipboard=unnamedplus
set cursorline
set encoding=utf-8
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set mouse=a
set noswapfile
set number
set numberwidth=1
set ruler
set shiftwidth=4
set showcmd
set showmatch
set softtabstop=4
set smartcase
set smartindent
set smarttab
set splitright
set tabstop=4
